# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chuck Norris Desafio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	
  # Pods for Chuck Norris Desafio
	pod 'RxSwift'
  	pod 'RxCocoa'
  target 'Chuck Norris DesafioTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'Chuck Norris DesafioUITests' do
    # Pods for testing
  end

end
